// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountSelectionUpdatedNotification = { threadId: string, selectedAccountId: string | null,
/**
 * Monotonic revision of this thread's selected-account state.
 */
selectionRevision: number, };
