// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

/**
 * Sparse rolling rate-limit update.
 *
 * Clients should merge available values into the most recent `account/rateLimits/read` response
 * or refetch that snapshot. Nullable account metadata may be unavailable in a rolling update and
 * does not clear a previously observed value.
 */
export type AccountRateLimitsUpdatedNotification = {
/**
 * Stable managed OAuth identity, or `null` for every non-pooled auth mode.
 */
managedAccountId: string | null,
/**
 * Managed account row revision, or `null` for every non-pooled auth mode.
 */
accountRevision: number | null, rateLimits: RateLimitSnapshot, };
