// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountAnalyticsReport } from "./AccountAnalyticsReport";
import type { AccountAnalyticsTaskParams } from "./AccountAnalyticsTaskParams";

export type AccountAnalyticsQuery = { "type": "validate" } | { "type": "account" } | { "type": "profile" } | { "type": "planHistory" } | { "type": "history", report: AccountAnalyticsReport,
/**
 * Inclusive UTC dates in YYYY-MM-DD form.
 */
start: string, end: string, } | { "type": "threads", ids: Array<string>, } | { "type": "tasks", threads: Array<AccountAnalyticsTaskParams>, };
