// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedChatgptAccountUsage } from "./ManagedChatgptAccountUsage";

export type AccountUsageUpdatedNotification = { managedAccountId: string,
/**
 * Revision of the managed account row carrying this usage observation.
 */
accountRevision: number, usage: ManagedChatgptAccountUsage, };
