// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedChatgptAccountView } from "./ManagedChatgptAccountView";

export type AccountPoolUpdatedNotification = { accounts: Array<ManagedChatgptAccountView>,
/**
 * Monotonic revision of global account-pool membership and account data.
 */
poolRevision: number, };
