// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountAnalyticsCreditBreakdown } from "./AccountAnalyticsCreditBreakdown";

export type AccountAnalyticsReport = { "type": "usage" } | { "type": "enterpriseTokens" } | { "type": "credits" } | { "type": "workspaceCredits" } | { "type": "enterpriseCredits", breakdown: AccountAnalyticsCreditBreakdown, } | { "type": "messages" } | { "type": "plugins", limit: number, } | { "type": "skills", limit: number, };
