// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Non-secret identity of a captured account, credential generation, and policy.
 */
export type AccountAnalyticsBinding = { threadId: string | null, sessionId: string | null, managedAccountId: string | null, accountId: string, userId: string, credentialRevision: number | null, routingRevision: number, policyRevision: number, };
