// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedChatgptAccountView } from "./ManagedChatgptAccountView";

export type ListAccountsResponse = { accounts: Array<ManagedChatgptAccountView>, selectedAccountId: string | null,
/**
 * Scoped selected-account revision when the list was requested for a thread,
 * or `null` for an unscoped list.
 */
selectionRevision: number | null,
/**
 * Monotonic revision of global account-pool membership and account data.
 */
poolRevision: number, };
