// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for the canonical managed ChatGPT account-pool listing.
 */
export type ListAccountsParams = {
/**
 * Selects the account pinned to this thread when present.
 */
threadId?: string | null,
/**
 * Model used when computing a scoped account selection.
 */
model?: string | null,
/**
 * Refresh due managed OAuth tokens before returning the list.
 */
refreshTokens?: boolean,
/**
 * Refresh account usage before returning the list.
 */
refreshUsage?: boolean, };
