// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedChatgptAccountView } from "./ManagedChatgptAccountView";

export type LogoutAccountResponse = { removedAccountIds: Array<string>, accounts: Array<ManagedChatgptAccountView>, selectedAccountId: string | null, };
