// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness and availability of a managed account's usage observation.
 */
export type ManagedChatgptAccountUsageState = "unknown" | "fresh" | "stale" | "unavailable";
