// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountTokenUsageSummary } from "./AccountTokenUsageSummary";
import type { ManagedChatgptAccountUsageState } from "./ManagedChatgptAccountUsageState";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

/**
 * Account-keyed usage data. Rate-limit entries carry their own `limitId`, so
 * additional metered limits cannot be mistaken for the singular compatibility
 * projection returned by `account/rateLimits/read`.
 */
export type ManagedChatgptAccountUsage = { state: ManagedChatgptAccountUsageState, rateLimits: Array<RateLimitSnapshot>, tokenUsage: AccountTokenUsageSummary | null,
/**
 * Unix timestamp in seconds for the retained observation.
 */
observedAt: number | null,
/**
 * Diagnostic text for `unavailable`, or `null` for other states.
 */
unavailableReason: string | null,
/**
 * Unix timestamp in seconds for the failed refresh represented by
 * `unavailable_reason`. This is independent from the retained successful
 * observation timestamp.
 */
unavailableObservedAt: number | null, };
