// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An active account block or cooldown.
 */
export type ManagedChatgptAccountBlock = {
/**
 * Stable machine-readable classification supplied by the account-pool owner.
 */
reason: string,
/**
 * Unix timestamp in seconds when the cooldown expires. `null` means the
 * block has no known automatic expiry.
 */
blockedUntil: number | null, };
