// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of the most recent managed OAuth token refresh.
 *
 * This is intentionally separate from selection eligibility, account blocks,
 * and usage freshness. Failure variants contain only stable, non-secret
 * metadata and never carry backend error text.
 */
export type ManagedChatgptAccountRefreshStatus = { "type": "healthy" } | { "type": "transientUnavailable",
/**
 * Unix timestamp in seconds when the refresh outcome was observed.
 */
observedAt: number, } | { "type": "reloginRequired",
/**
 * Stable machine-readable classification; never raw backend text.
 */
reasonCode: string,
/**
 * Unix timestamp in seconds when the refresh outcome was observed.
 */
observedAt: number, };
