// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanType } from "../PlanType";
import type { ManagedChatgptAccountBlock } from "./ManagedChatgptAccountBlock";
import type { ManagedChatgptAccountRefreshStatus } from "./ManagedChatgptAccountRefreshStatus";
import type { ManagedChatgptAccountUsage } from "./ManagedChatgptAccountUsage";

/**
 * Public managed-OAuth account view.
 *
 * `managed_account_id` is the stable identity used to key every other field in
 * this row. Consumers must not join account data by array position, email, or
 * the optional raw ChatGPT account ID.
 */
export type ManagedChatgptAccountView = { managedAccountId: string, chatgptAccountId: string | null, email: string | null, planType: PlanType, eligible: boolean, eligibilityReason: string | null, accountRevision: number,
/**
 * Monotonic revision of the credential generation backing this account.
 *
 * Unlike `account_revision`, status and usage observations do not change it.
 */
credentialRevision: number, refreshStatus: ManagedChatgptAccountRefreshStatus, block: ManagedChatgptAccountBlock | null, usage: ManagedChatgptAccountUsage, };
